server:
  port: 9009
spring:
  application:
    name: leadnews-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.85.143:8848
  elasticsearch:
    rest:
      uris: http://192.168.85.143:9200
  data:
    mongodb:
      host: 192.168.85.143
      port: 27017
      database: leadnews_history
