server:
  port: 9007
spring:
  application:
    name: leadnews-comment
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.85.143:8848
  data:
    mongodb:
      host: 192.168.85.143
      port: 27017
      database: leadnews_comment
  redis:
    host: 192.168.85.143
