server:
  port: 6002
spring:
  application:
    name: leadnews-media-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.85.143:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 自媒体微服务
        - id: media
          uri: lb://leadnews-media
          predicates:
            - Path=/media/**
          filters:
            - StripPrefix= 1
